language: c
sudo: false
before_install:
  - sudo apt-get -qq update
  # - sudo apt-get install -y doxygen doxygen-doc doxygen-latex doxygen-gui graphviz
  - sudo apt-get install -y curl
  - export DOXYGEN_VERSION=1.8.13
  - curl -LO "http://ftp.stack.nl/pub/users/dimitri/doxygen-$DOXYGEN_VERSION.linux.bin.tar.gz"
  - tar xvf doxygen-$DOXYGEN_VERSION.linux.bin.tar.gz
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/doxygen-$DOXYGEN_VERSION/bin
  - source <(curl -SLs https://raw.githubusercontent.com/bakercp/travis-ci-arduino/master/install.sh)
install:
  - arduino --install-library "ArduinoUnit"
script:
  - build_main_platforms
  - cd docs
  - doxygen Doxyfile
notifications:
  email:
    on_success: change
    on_failure: change
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: $TRAVIS_BUILD_DIR/docs/html/
  target_branch: gh-pages
  name: Christopher Baker
  email: info@christopherbaker.net
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
